//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Convert> Converts { get; set; }
        public virtual DbSet<Convert_Categories> Convert_Categories { get; set; }
        public virtual DbSet<Export> Exports { get; set; }
        public virtual DbSet<Export_Categories> Export_Categories { get; set; }
        public virtual DbSet<Import> Imports { get; set; }
        public virtual DbSet<Import_Categories> Import_Categories { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
    
        public virtual ObjectResult<catagoriesExpiredPeroid_Result> catagoriesExpiredPeroid(Nullable<int> period)
        {
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<catagoriesExpiredPeroid_Result>("catagoriesExpiredPeroid", periodParameter);
        }
    
        public virtual ObjectResult<catogoryReport_Result> catogoryReport(string catogoryCode)
        {
            var catogoryCodeParameter = catogoryCode != null ?
                new ObjectParameter("catogoryCode", catogoryCode) :
                new ObjectParameter("catogoryCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<catogoryReport_Result>("catogoryReport", catogoryCodeParameter);
        }
    
        public virtual ObjectResult<catogoryReportWithDate_Result> catogoryReportWithDate(string catogoryCode, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var catogoryCodeParameter = catogoryCode != null ?
                new ObjectParameter("catogoryCode", catogoryCode) :
                new ObjectParameter("catogoryCode", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<catogoryReportWithDate_Result>("catogoryReportWithDate", catogoryCodeParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<ReportAboutCatogoriesMovement_Result> ReportAboutCatogoriesMovement(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReportAboutCatogoriesMovement_Result>("ReportAboutCatogoriesMovement", idParameter);
        }
    
        public virtual ObjectResult<warehouse_data_Result> warehouse_data(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<warehouse_data_Result>("warehouse_data", idParameter);
        }
    
        public virtual ObjectResult<warehouse_data_startDate_endDate_Result> warehouse_data_startDate_endDate(Nullable<int> id, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<warehouse_data_startDate_endDate_Result>("warehouse_data_startDate_endDate", idParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<warehouse_data_with_Period_Result> warehouse_data_with_Period(Nullable<int> id, Nullable<int> period)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<warehouse_data_with_Period_Result>("warehouse_data_with_Period", idParameter, periodParameter);
        }
    }
}
